### ISSUE TITLE
HomeyAPI.ManagerInsights.getEntries gives timeout for large datasets

### ISSUE THREAD

**Issue by gruijter** [athombv/node-athom-api#1]
I'm getting a timeout on the web-api (athom-api) when I want to read the entries of a log that contains a lot of data. For smaller logs I do not get this error.

```
{ Error: Timed out after 30000ms.
    at Timeout.<anonymous> (/node_modules/athom-api/dist/index.js:1:865791)
    at ontimeout (timers.js:475:11)
    at Timer.unrefdHandle (timers.js:588:5) code: 'TIMEOUT' }
```

Questions:
* How can I avoid a timeout
* Is it possible to get a stream of the entries (this was possible in the old api)

**Comment by gruijter** [comment]
I made an issue of this in :
https://github.com/athombv/homey-issues-dp/issues/135
